### PR TITLE
GCS: Fix logic for falling back to Google defaults

### LINKED ISSUE #104: Enable GCS to work with GKE workload identity
https://github.com/thanos-io/objstore/pull/86#discussion_r1505128594 I believe that this line would prevent the storage client from being able to use the environment variable `GOOGLE_APPLICATION_CREDENTIALS`. If the `service_account` field is not provided, there is no way to authenticate anymore via GKE workload identity (which was previously supported).

More context: https://cloud-native.slack.com/archives/CK5RSSC10/p1633961188039700
https://cloud-native.slack.com/archives/CK5RSSC10/p1708022085482559
https://pkg.go.dev/cloud.google.com/go/storage#NewClient

### PR DESCRIPTION
**Pull request by saswatamcode**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

Fixes #104

### CODE REVIEW

**Review by JoaoBraveCoding — APPROVED** [review]
lgtm

**Comment by jhalterman** [comment]
Unfortunately this didn't resolve the issue for us. When dropping the latest Thanos with this PR into our app, with no other changes, we're getting:
```
oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_scope\",\"error_description\":\"Invalid OAuth scope or ID token audience provided.\"
```

**Comment by saswatamcode** [comment]
Could you provide more details as to how it was failing before? Was it the same error?

**Comment by jhalterman** [comment]
This is a new error that only happens after we updated our objstore dependency to include the changes from #86 and this PR.

**Pull request merged**
