### PR TITLE
s3:bump aws-sdk-go-v2/config for aws service endpoint env vars

### PR DESCRIPTION
**Pull request by matthewhudsonedb**
* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

s3:bump aws-sdk-go-v2/config for aws service endpoint env vars

### CODE REVIEW

**Review by Anhui-tqhuang — APPROVED** [review]

**Review by yeya24 — COMMENTED** [review]
The PR looks good. Can you please fix conflicts?

**Comment by matthewhudsonedb** [comment]
@yeya24 conflicts have been fixed

**Review by JoaoBraveCoding — APPROVED** [review]
lgtm

**Comment by matthewhudsonedb** [comment]
@JoaoBraveCoding @yeya24 another conflict for release notes appeared which I've also fixed.

**Pull request merged**
