### PR TITLE
Add OCI Object Storage Bucket support

### PR DESCRIPTION
**Pull request by aarontams**
* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

#### Add Oracle Cloud Infrastructure (OCI) Object Storage Bucket support
OCI Object Storage supports three different providers, default, instance principle, and raw. A lot of OCI users like to use Instance principle to security. It is very important to support instance principle for the OCI users. `S3 doesn't support OCI instance principle.` 

#### Support multiple prometheus instances with a single bucket 
By default, like other clients, this new Thanos OCI Object Storage client will storage the data from a single prometheus instance to the top directory of the bucket. This means each bucket can only store one prometheus instance data.

In OCI, a lot of users like to put different type of data in a single bucket.
To support multiple prometheus instances with a single bucket, a new object_base_path option is introduced in this OCI Object Storage client. If defined, the value will be used as the prefix of the prometheus data in OCI bucket.

For example, if you want to use the same bucket for 2 prometheus instances, you can define object_base_path as /path/for/prometheus1 for the first prometheus instance, and /path/for/prometheus2 for the second prometheus instance.

Three tests are included here to demo how the object_base_path work.

## Verification
From original [PR](https://github.com/thanos-io/thanos/pull/4661): Running similar OCI client against 3 prometheus instances for over 50 days without any issue.
For each prometheus instance
- average 4.5GB (2GB in chunks and 2.5G index) per 2-hour prometheus block
- over 50GB per day
- over 2TB prometheus data uploaded to OCI Object Storage
oci storage 1
oci storage 2

### Testing from this PR
```
export THANOS_TEST_OBJSTORE_SKIP=GCS,S3,AZURE,SWIFT,COS,ALIYUNOSS,BOS
// export OCI_* required variables
$ make test
go test ./...
ok  	github.com/thanos-io/objstore	(cached)
?   	github.com/thanos-io/objstore/client	[no test files]
ok  	github.com/thanos-io/objstore/clientutil	(cached)
?   	github.com/thanos-io/objstore/errutil	[no test files]
ok  	github.com/thanos-io/objstore/exthttp	(cached)
ok  	github.com/thanos-io/objstore/objtesting	123.749s
ok  	github.com/thanos-io/objstore/providers/azure	(cached)
?   	github.com/thanos-io/objstore/providers/bos	[no test files]
ok  	github.com/thanos-io/objstore/providers/cos	(cached)
ok  	github.com/thanos-io/objstore/providers/filesystem	(cached)
ok  	github.com/thanos-io/objstore/providers/gcs	(cached)
?   	github.com/thanos-io/objstore/providers/oci	[no test files]
?   	github.com/thanos-io/objstore/providers/oss	[no test files]
ok  	github.com/thanos-io/objstore/providers/s3	(cached)
ok  	github.com/thanos-io/objstore/providers/swift	(cached)
?   	github.com/thanos-io/objstore/scripts/cfggen	[no test files]
?   	github.com/thanos-io/objstore/test/e2e/e2ethanos	[no test files]
?   	github.com/thanos-io/objstore/tracing	[no test files]
```
See the test steps in README.md under OCI section.

image

##### Original PR: https://github.com/thanos-io/thanos/pull/4661

### CODE REVIEW

**Comment by aarontams** [comment]
^^^ @kakkoyun and @yeya24 @GiedriusS @wiardvanrij @Djelibeybi

**Review by wiardvanrij — COMMENTED** [review]
lgtm, just add a readme and we should be good to go.

**Comment by aarontams** [comment]
Thanks @wiardvanrij for reviewing it.
I added the changelog: https://github.com/thanos-io/objstore/pull/15/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR16

**Review by kakkoyun — APPROVED** [review]
LGTM. Thanks for the hard work and patience :hugs:

**Comment by GiedriusS** [comment]
:tada:

**Comment by wiardvanrij** [comment]
Yea thanks @aarontams  :)

**Comment by wiardvanrij** [comment]
https://twitter.com/ThanosMetrics/status/1549071260415660032 :)

**Comment by kakkoyun** [comment]
We haven't actually discussed the cadence of the updates of objstore among Thanos maintainers (assuming at the very least before each major release), however, if you want to immediately have this on Thanos main branch, @aarontams  you should send another PR to Thanos main repo to bump up the dependency version.

**Pull request merged**
