### PR TITLE
feat: add MaxRetires config to cos, gcs and obs

### PR DESCRIPTION
**Pull request by ashwanthgoli**
* [x] I added CHANGELOG entry for this change.
* [ ] Change is not relevant to the end user.

## Changes

~~Adds a configuration option for GCS to disable retries. GCS client retries idempotent operations by default.
This allows disabling retries incase someone wants to handle them at a higher level~~

Introduces `MaxRetries` configuration for gcs, cos and obs providers.

Already supported by a few providers but the naming isn't consistent 
- Azure already [supports it](https://github.com/ashwanthgoli/objstore/blob/b07fd8d2dda4e2002fb8414b35e62fdcfd193ea7/providers/azure/azure.go#L56)
- Swift has a [Retries](https://github.com/ashwanthgoli/objstore/blob/b07fd8d2dda4e2002fb8414b35e62fdcfd193ea7/providers/swift/swift.go#L66) config
- oci has [MaxRequestRetries](https://github.com/ashwanthgoli/objstore/blob/b07fd8d2dda4e2002fb8414b35e62fdcfd193ea7/providers/oci/oci.go#L83) config

Not supported yet by the following:
- s3 i raised an [upstream pr](https://github.com/minio/minio-go/pull/2013), i'll make a follow-up change once that is merged
- bos supports disabling retries with `bce.NewNoRetryPolicy()` but there is no public api to update max retries.
- oss does not support updating it, but i do not see the[ default retries](https://github.com/aliyun/aliyun-oss-go-sdk/blob/b6e0a2ae5b13f20fcdaf8e5c00b0bcf9dece0a34/oss/conf.go#L260) wired up either. So i am not sure if it does retries

### CODE REVIEW

**Review by JoaoBraveCoding — APPROVED** [review]
lgtm

**Comment by ashwanthgoli** [comment]
would really appreciate a review on this one, thank you!

**Comment by ashwanthgoli** [comment]
[minio-go v7.0.80](https://github.com/minio/minio-go/releases/tag/v7.0.80) adds support to configure retries, but it requires go@1.22

**Review by yeya24 — APPROVED** [review]
LGTM. Thanks!

**Review by fpetkovski — APPROVED** [review]

**Pull request merged**
