### PR TITLE
Fix remove file on download failed

### PR DESCRIPTION
**Pull request by hanjm**
* [ ] I added CHANGELOG entry for this change.
* [x] Change is not relevant to the end user.

## Changes

When thanos comactor download dir failed,  it will log some warn log `directory not empty`
```
{"caller":"objstore.go:386","err":"remove /var/thanos/compact/0@11467029899044838548/01GEP2RKFRS5XGV6DTESTS6XAV: directory not empty","file":"/var/thanos/compact/0@11467029899044838548/01GEP2RKFRS5XGV6DTESTS6XAV","group":"0@{tenant_id=\"xxx\"}","groupKey":"0@11467029899044838548","level":"warn","msg":"failed to remove file on partial dir download error","ts":"2022-10-23T05:02:18.363465578Z"}
```
this PR change to use `RemoveAll` instead of `Remove`,
`Remove removes the named file or (empty) directory.`
`RemoveAll` removes path and any children it contains.

### CODE REVIEW

**Comment by hanjm** [comment]
hi @yeya24 , could you help review. Thank you.

**Comment by hanjm** [comment]
hi @squat , could you help review this pr. Thank you.

**Comment by hanjm** [comment]
@squat  the DownloadDir function will download all files and sub dir. a block has index files and chunks dir.

**Comment by squat** [comment]
Ack makes sense 🌟

**Review by squat — APPROVED** [review]

**Comment by hanjm** [comment]
super rapid, Thanks.

**Pull request merged**
